config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
  	resources :items
  end
  
  devise_for :users
  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  after_save do

    if task.items.count == task.items.completed.count
      task.update!(completed: true)
    end
  end

  belongs_to :task

  scope :completed, -> { where(completed: true) }
end

app/models/task.rb
class Task < ApplicationRecord
	before_save do
		if completed_changed? && completed
			items.update_all(completed: true)
		elsif completed_changed? && !completed
			items.update_all(completed: false)
		end 
	end

	has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :redirect_to_sign_in

	def redirect_to_sign_in
		redirect_to :new_user_session if !user_signed_in? &&
																		 !request.path.include?('users')
	end 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    if user_signed_in?
      @items = current_user.items.order(created_at: :desc)
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @task = current_user.tasks.find(params.require(:task_id))
    @item = @task.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @task = current_user.tasks.find(params.require(:task_id))
    @item = @task.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to task_path(@task), notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to task_path(@task), notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to task_path(@item.task), notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def find_item
    @task = current_user.tasks.find(params.require(:task_id))
    @item = @task.items.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:item, :completed)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    if user_signed_in?
      @tasks = current_user.tasks.order(created_at: :desc)
    end
  end

  def show
    @task = current_user.tasks.find(params.require(:id))
  end
  def edit
    @task = current_user.tasks.find(params.require(:id))
  end

  def new
    @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @task = current_user.tasks.find(params.require(:id))
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task}
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task = current_user.tasks.find(params.require(:id))
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:title, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/items/_form.html.erb
<%= form_for [@task, @item] do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :item, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit 'Add', class: "btn btn-primary"%>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>


<%= link_to 'Back', task_path(@task) %>

app/views/items/index.html.erb
<% if user_signed_in? %>
	<% @items.each do |item| %>
		<p><%= item.item %></p>
		<p><%= item%></p>
	<% end %>
<% else %>
	<%= render 'welcome_page' %>
	<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', task_items_path(@task) %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item.item %>
</p>

<%= link_to 'Edit', edit_task_item_path(@task, @item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body style ="text-align: center">

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Todoster", root_path, class:"navbar-brand" %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user.present? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
          <% else  %>
          <li><%= link_to "Log In", new_user_session_path%> </li>
          <li><%=  link_to "Sign Up", new_user_registration_path%> </li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <%= link_to "Create Task", new_task_path, class:"navbar-text navbar-link"%>
          <% end %>
      </div>

    </nav>
  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit 'Add', class: "btn btn-primary"%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show items', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<% if user_signed_in? %>
	<% @tasks.each do |task| %>
		<p>
			<% if task.completed == true %>
		    	<%= link_to "Re-do", task_path(task) + '?task[completed]=false', method: :patch, class: 'btn btn-outline-danger btn-sm'%> 
				<s><%= link_to task.title, task_path(task) %></s>
		    <% else %>
		    	<%= link_to "Complete", task_path(task) + '?task[completed]=true', method: :patch, class: 'btn btn-outline-primary btn-sm'%>    	
				<%= link_to task.title, task_path(task) %>
			<% end %>
		</p>		
		<%= link_to "Edit", edit_task_path(task)  %>|
		<%= link_to "Delete", task_path(task), method: :delete, data: {confirm: "Are you sure?"} %>
		<hr>
	<% end %>

<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <strong><h2>Task: <%= @task.title.capitalize %></h2></strong><br>
  <% @task.items.each  do |item|%>
  	<% if item.completed == true %>
		<%= link_to "Re-do", task_item_path(@task, item) + '?item[completed]=false', method: :patch, class: 'btn btn-outline-danger btn-sm'%> 
		<s><%= item.item %>|</s>
	<% else %>
	    <%= link_to "Complete", task_item_path(@task, item) + '?item[completed]=true', method: :patch, class: 'btn btn-outline-primary btn-sm'%>    	
		<%= item.item %>|
	<% end %>
  <%= link_to "Edit", edit_task_item_path(@task, item) %>|
  <%= link_to "Delete", task_item_path(@task, item), method: :delete, data: {confirm: "Are you sure?"} %></br>
  <hr>
  <% end %>
</p>
<%= link_to 'Add item', new_task_item_path(@task) %> |
<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>